implement mysql
YunoHost-Apps/galette_ynh pull request #26
Opened 2022-04-13 22:34 UTC by yalh76

## Problem

- *congressus_ynh require a mysql galette*

## Solution

- *implement mysql*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-04-13 22:34 UTC, yalh76 commented
!testme

2022-04-14 05:28 UTC, ericgaspar requested changes

2022-04-14 05:28 UTC, ericgaspar commented on conf/config.inc.php.mysql
> +define("USER_DB", "__DB_NAME__");
```suggestion
define("USER_DB", "__DB_USER__");
```

2022-04-14 06:21 UTC, yalh76 commented on conf/config.inc.php.mysql
> +define("USER_DB", "__DB_NAME__");
Fixed ^^

2022-04-14 06:21 UTC, yalh76 commented
!testme

2022-04-14 17:41 UTC, yalh76 commented
!testme

2022-04-14 23:29 UTC, yalh76 commented
!testme

2022-04-15 17:56 UTC, merged